In [113]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings('ignore')

In [91]:
company_data = pd.read_csv('Company_Data.csv')
company_data

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [92]:
company_data.shape

(400, 11)

In [93]:
company_data.isna().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [94]:
company_data.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc       object
Age              int64
Education        int64
Urban           object
US              object
dtype: object

In [95]:
from sklearn.preprocessing import LabelEncoder
le_encoder=LabelEncoder()
company_data['ShelveLoc'] = le_encoder.fit_transform(company_data['ShelveLoc'])
company_data['Urban'] = le_encoder.fit_transform(company_data['Urban'])
company_data['US'] = le_encoder.fit_transform(company_data['US'])
company_data

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0     9.50        138      73           11         276    120          0   42   
1    11.22        111      48           16         260     83          1   65   
2    10.06        113      35           10         269     80          2   59   
3     7.40        117     100            4         466     97          2   55   
4     4.15        141      64            3         340    128          0   38   
..     ...        ...     ...          ...         ...    ...        ...  ...   
395  12.57        138     108           17         203    128          1   33   
396   6.14        139      23            3          37    120          2   55   
397   7.41        162      26           12         368    159          2   40   
398   5.94        100      79            7         284     95          0   50   
399   9.71        134      37            0          27    120          1   49   

     Education  Urban  US  
0           17      1   1  
1           10      1   1  
2           12      1   1  
3           14      1   1  
4           13      1   0  
..         ...    ...  ..  
395         14      1   1  
396         11      0   1  
397         18      1   1  
398         12      1   1  
399         16      1   1  

[400 rows x 11 columns]

In [96]:
company_data.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc        int32
Age              int64
Education        int64
Urban            int32
US               int32
dtype: object

In [97]:
X=company_data.drop(['ShelveLoc'],axis=1)
y=company_data[['ShelveLoc']]

In [98]:
X.shape,y.shape

((400, 10), (400, 1))

In [99]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=12)

In [100]:
X_train.shape,y_train.shape

((320, 10), (320, 1))

In [101]:
X_test.shape,y_test.shape

((80, 10), (80, 1))

In [102]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=100,max_depth=4)
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(max_depth=4)

In [103]:
from sklearn.model_selection import GridSearchCV
grid_search_cv=GridSearchCV(estimator=rf_classifier,param_grid={'criterion':['entropy','gini'],
                                           'max_depth':[1,2,3,4,5,6,7,8,9,10]},
                                            cv=5
                                           )
grid_search_cv.fit(X,y)
print(grid_search_cv.best_params_)
print(grid_search_cv.best_score_)

{'criterion': 'entropy', 'max_depth': 9}
0.6450000000000001


In [104]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=100,max_depth=9,criterion='entropy')
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=9)

In [105]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [106]:
y_train_pred = rf_classifier.predict(X_train)
y_train_pred

array([2, 2, 0, 2, 2, 1, 2, 2, 0, 1, 2, 1, 1, 1, 2, 2, 0, 0, 2, 1, 2, 0,
       2, 1, 1, 2, 2, 2, 2, 2, 2, 0, 1, 2, 0, 0, 1, 2, 2, 0, 1, 2, 0, 2,
       2, 1, 0, 1, 1, 1, 1, 2, 2, 2, 1, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 1,
       0, 1, 2, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 2, 2, 2, 0, 2, 2, 0, 1,
       2, 2, 0, 0, 2, 2, 1, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 0, 2, 2, 1, 1, 0, 0, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0, 1,
       1, 2, 2, 1, 1, 1, 2, 2, 2, 0, 2, 1, 2, 2, 1, 0, 2, 2, 2, 2, 2, 0,
       2, 1, 1, 2, 2, 1, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0,
       2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2, 2, 1, 2, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 2, 2,
       2, 2, 1, 2, 1, 2, 0, 0, 1, 2, 1, 2, 0, 2, 1,

In [107]:
accuracy_score(y_train,y_train_pred)

0.996875

In [108]:
confusion_matrix(y_train,y_train_pred)

array([[ 79,   0,   0],
       [  0,  63,   1],
       [  0,   0, 177]], dtype=int64)

In [109]:
y_test_pred=rf_classifier.predict(X_test)
y_test_pred

array([0, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 0, 1, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 0, 1, 2, 1, 1, 0, 2, 2, 2])

In [110]:
accuracy_score(y_test,y_test_pred)

0.6875

In [111]:
confusion_matrix(y_test,y_test_pred)

array([[ 8,  0,  9],
       [ 0,  8, 13],
       [ 2,  1, 39]], dtype=int64)